unbind r
bind r source-file ~/.tmux.conf

set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Set prefix to Ctrl-a
set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

bind-key C-n next-window
bind-key C-p previous-window
bind-key C-[ copy-mode

bind-key | split-window -h
bind-key - split-window -v

bind-key -T copy-mode-vi 'v' send-keys -X begin-selection
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection

set -g history-limit 8192
set -g renumber-windows on
set -g status-justify absolute-centre

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

set-window-option -g mode-keys vi
set-option -g status-position top

set -g default-terminal "tmux-256color"
# Enable true color support
set-option -ga terminal-overrides ",alacritty*:Tc,tmux-256color:Tc,*256col*:Tc"
set-option -ga terminal-features ",alacritty*:RGB,tmux-256color:RGB,*256col*:RGB"
set-option -g set-clipboard on

set -g allow-passthrough on

set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_number "#[fg=#{@thm_fg}]#I"
set -g @catppuccin_window_current_text "#[fg=#{@thm_mauve},bold]#W"
set -g @catppuccin_window_current_number "#[fg=#{@thm_mauve},bold]#I"
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_number_color "#{@catppuccin_status_background}"
set -g @catppuccin_window_text_color "#{@catppuccin_status_background}"
set -g @catppuccin_window_current_number_color "#{@thm_surface_0}"
set -g @catppuccin_window_current_text_color "#{@thm_surface_0}"
set -g @catppuccin_session_icon ""
set -g @catppuccin_session_color "#{@thm_surface_0}"
set -g @catppuccin_status_session_icon_bg "#{@thm_surface_0}"
set -g @catppuccin_status_session_text_bg "#{@thm_surface_0}"
set -g @catppuccin_status_left_separator ""
set -g @catppuccin_status_right_separator " "

run '~/.tmux/plugins/tpm/tpm'
run '~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux'

set -g status-right-length 100
set -g status-left-length 100
set -gF status-left "#[fg=#{@thm_fg},bg=#{@thm_surface_0},us=#{@thm_surface_1}] ##S #[default]"
set -gF status-right "#[fg=#{@thm_fg},bg=#{@thm_surface_0},us=#{@thm_surface_1}] %l:%M %p #[default]"
