return {
	{ src = "https://github.com/nvim-tree/nvim-web-devicons", name = "nvim-web-devicons" },
	{ src = "https://github.com/github/copilot.vim", name = "copilot.vim" },
	{ src = "https://github.com/rafamadriz/friendly-snippets", name = "friendly-snippets" },
	{ src = "https://github.com/saghen/blink.cmp", name = "blink.cmp", version = vim.version.range("1.*") },
	{ src = "https://github.com/j-hui/fidget.nvim", name = "fidget.nvim" },
	{ src = "https://github.com/stevearc/conform.nvim", name = "conform.nvim" },
	{ src = "https://github.com/tpope/vim-fugitive", name = "vim-fugitive" },
	{ src = "https://github.com/tpope/vim-rhubarb", name = "vim-rhubarb" },
	{ src = "https://github.com/lewis6991/gitsigns.nvim", name = "gitsigns.nvim" },
	{ src = "https://github.com/lukas-reineke/indent-blankline.nvim", name = "indent-blankline.nvim" },
	{ src = "https://github.com/williamboman/mason.nvim", name = "mason.nvim" },
	{ src = "https://github.com/williamboman/mason-lspconfig.nvim", name = "mason-lspconfig.nvim" },
	{ src = "https://github.com/neovim/nvim-lspconfig", name = "nvim-lspconfig" },
	{ src = "https://github.com/folke/lazydev.nvim", name = "lazydev.nvim" },
	{ src = "https://github.com/folke/trouble.nvim", name = "trouble.nvim" },
	{ src = "https://github.com/nvim-lualine/lualine.nvim", name = "lualine.nvim" },
	{ src = "https://github.com/iamcco/markdown-preview.nvim", name = "markdown-preview.nvim" },
	{ src = "https://github.com/nvim-mini/mini.nvim", name = "mini.nvim" },
	{ src = "https://github.com/MeanderingProgrammer/render-markdown.nvim", name = "render-markdown.nvim" },
	{ src = "https://github.com/MunifTanjim/nui.nvim", name = "nui.nvim" },
	{ src = "https://github.com/folke/noice.nvim", name = "noice.nvim" },
	{ src = "https://github.com/rcarriga/nvim-notify", name = "nvim-notify" },
	{ src = "https://github.com/stevearc/oil.nvim", name = "oil.nvim" },
	{ src = "https://github.com/folke/snacks.nvim", name = "snacks.nvim" },
	{ src = "https://github.com/rebelot/kanagawa.nvim", name = "kanagawa.nvim" },
	{ src = "https://github.com/tpope/vim-commentary", name = "vim-commentary" },
	{ src = "https://github.com/tpope/vim-surround", name = "vim-surround" },
	{ src = "https://github.com/christoomey/vim-tmux-navigator", name = "vim-tmux-navigator" },
}
