[colors.primary]
background = '#11131a'
foreground = '#e1e2eb'

[colors.selection]
text = '#e1e2eb'
background = '#4d8efe'

[colors.cursor]
text = '#11131a'
cursor = '#adc6ff'

[colors.normal]
black   = '#11131a'
red     = '#ff7299'
green   = '#7fff92'
yellow  = '#fff872'
blue    = '#94b1f2'
magenta = '#304576'
cyan    = '#adc6ff'
white   = '#eff4ff'

[colors.bright]
black   = '#999da5'
red     = '#ff9fb9'
green   = '#a5ffb3'
yellow  = '#fffaa5'
blue    = '#b9ceff'
magenta = '#c5d7ff'
cyan    = '#dae5ff'
white   = '#f8faff'
