[colors.primary]
background = '#0d1418'
foreground = '#dce4e9'

[colors.selection]
text = '#dce4e9'
background = '#564500'

[colors.cursor]
text = '#0d1418'
cursor = '#e2c462'

[colors.normal]
black   = '#0d1418'
red     = '#ff6e60'
green   = '#74e261'
yellow  = '#ffe560'
blue    = '#d6b444'
magenta = '#685000'
cyan    = '#e2c462'
white   = '#ede9dd'

[colors.bright]
black   = '#929086'
red     = '#ff9c92'
green   = '#a8ff99'
yellow  = '#ffee99'
blue    = '#f8dc80'
magenta = '#ffe799'
cyan    = '#ffefbe'
white   = '#fffdf7'
