[colors.primary]
background = '#12131a'
foreground = '#e3e1ec'

[colors.selection]
text = '#e3e1ec'
background = '#1c511f'

[colors.cursor]
text = '#12131a'
cursor = '#9bd595'

[colors.normal]
black   = '#12131a'
red     = '#f48d6e'
green   = '#6dd56a'
yellow  = '#ffee72'
blue    = '#88ca81'
magenta = '#31622c'
cyan    = '#9bd595'
white   = '#d3dfd2'

[colors.bright]
black   = '#818a80'
red     = '#ffb59f'
green   = '#a8ffa5'
yellow  = '#fff4a5'
blue    = '#b4eaae'
magenta = '#ceffc9'
cyan    = '#dfffdc'
white   = '#f9fff8'
